default: &default
  image:
    default_poster: 'http://wifi.smbiztalk.cn/uploads/poster/telecom.png'
  alipay:
    pid: '2088402465243298'
    secret: 'p182a5k2yekoo5fzjjcbpysu41ak4wlb'
    seller_email: 'myemail@gmail.com'
    return_url: 'http://mysite.com/orders/done'
    notify_url: 'http://mysite.com/orders/notify'

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: ''
